name: Release Weekly Docker
on:
  push:
    branches:
      - "feature/zap-arm-builds-debug"
  workflow_dispatch:
  repository_dispatch:
    types: 'release-weekly-docker'

jobs:
  publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "REL_DATE=$(date +%F)" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: j12934
          password: ${{ secrets.ZAPBOT_DOCKER_TOKEN }}
      -
        name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: docker
          file: docker/Dockerfile-stable
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            j12934/zap2docker-weekly:w${{ env.REL_DATE }}
            j12934/zap2docker-weekly:latest
          build-args: |
            WEBSWING_URL=${{ secrets.WEBSWING_URL }}
