name: Release Main Docker

on:
  push:
    branches:
      - "feature/zap-arm-builds-debug"
  workflow_dispatch:
  repository_dispatch:
    types: 'release-main-docker'

jobs:
  publish:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get install xmlstarlet
          echo "REL_VERSION=$(curl -s https://raw.githubusercontent.com/zaproxy/zap-admin/master/ZapVersions.xml | xmlstarlet sel -t -v //core/version)" >> $GITHUB_ENV
          echo "REL_DATE=$(date +%F)" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: j12934
          password: ${{ secrets.ZAPBOT_DOCKER_TOKEN }}
      - 
        name: Build stable Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: docker
          file: docker/Dockerfile-stable
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            j12934/zap2docker-stable:s${{ env.REL_DATE }}
            j12934/zap2docker-stable:${{ env.REL_VERSION }}
            j12934/zap2docker-stable:latest
          build-args: |
            WEBSWING_URL=${{ secrets.WEBSWING_URL }}
      -
        name: Build bare Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: docker
          file: docker/Dockerfile-bare
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            j12934/zap2docker-bare:b${{ env.REL_DATE }}
            j12934/zap2docker-bare:${{ env.REL_VERSION }}
            j12934/zap2docker-bare:latest

